#!/bin/sh
# printf "Nombre d'arguments : $#\n"
case $# in
0 | 1)
	printf "Nombre d'arguments insuffisant !\n"
	;;
2)
	printf '%d\n' $(($1 + $2))
	;;
3)
	case $3 in
	+ | - | \* | / | %)
		printf '%d\n' $(($1 $3 $2))
		break
		;;
	*)
		printf '%s : Opération non prise en charge\n' $3
		break
	esac
	;;
*)
	printf "Trop d'arguments : entrer 2 ou 3 arguments\n"
	;;
esac
